
# After registering a name on build.snapcraft.io, commit an uncommented line:
name: tux-football
version: '0.3.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tux Football, a fun arcade-style 2D football game. # 79 char long summary
description: |
  Tux Football, a fun arcade-style 2D football game for Windows and Linux,
  very reminsicent of Sensible Soccer and Kick Off.

# icon: snap/gui/icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core18

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  
apps:
  tux-football:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: bin/tuxfootball
    environment:
      # pulseaudio
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      # ALSA_CONFIG_PATH: ${SNAP}/etc/asound.conf
      # PULSE_SYSTEM: 1
      # PULSE_RUNTIME_PATH: /var/run/pulse
      # PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native
    extensions: [gnome-3-28]
    plugs:
      - audio-playback
      - pulseaudio
      - alsa
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - gsettings
        
layout:
  /usr/share/midi/freepats:
    bind: $SNAP/usr/share/midi/freepats
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/local/doc:
    bind: $SNAP/doc
  /usr/local/share/appdata:
    bind: $SNAP/share/appdata
  /usr/local/share/icons:
    bind: $SNAP/share/icons
  /usr/local/share/locale:
    bind: $SNAP/usr/share/locale
  /usr/local/share/tuxfootball:
    bind: $SNAP/share/tuxfootball
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/timidity:
    bind: $SNAP/etc/timidity
  /etc/fonts:
    bind: $SNAP/etc/fonts
    
parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  tux-football:
    after: [alsa-mixin]
    plugin: cmake
    source: "https://git.code.sf.net/p/tuxfootball/code"
    source-depth: 1
    source-branch: master
    source-type: git
    build-packages:
      - gcc
      - g++
      - cmake
      - make
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
  
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - freepats
      - libmodplug1
      - libopusfile0
      - libpulse0
      - libsndfile1
